repos:
  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
        args: [ --safe, --config=./pyproject.toml ]
        exclude: "docs"

  - repo: https://github.com/LilSpazJoekp/docstrfmt
    rev: v1.6.1
    hooks:
      - id: docstrfmt
        args:
          - "-l 160"

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: debug-statements
        language_version: python3

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev:  v0.3.1
    hooks:
      - id: ruff
        args: [ --config=./pyproject.toml ]
